// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4I2V9mM0Bxba2YgjuNdMVrtlQ5GTtmBs',
    appId: '1:291688942373:web:17d0b4119508d0dda1a8cc',
    messagingSenderId: '291688942373',
    projectId: 'gdsc-53961',
    authDomain: 'gdsc-53961.firebaseapp.com',
    storageBucket: 'gdsc-53961.appspot.com',
    measurementId: 'G-S14R1HJV6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDHouZLuqdYs5hpLYVwygxiRwq0AXzVQ4',
    appId: '1:291688942373:android:1624784f42267860a1a8cc',
    messagingSenderId: '291688942373',
    projectId: 'gdsc-53961',
    storageBucket: 'gdsc-53961.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEK1w5EkFRb0fHpb8NuC5iQx4UKtPkJf8',
    appId: '1:291688942373:ios:cdf1b3b8c9e6dd0fa1a8cc',
    messagingSenderId: '291688942373',
    projectId: 'gdsc-53961',
    storageBucket: 'gdsc-53961.appspot.com',
    iosBundleId: 'com.example.gdsc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEK1w5EkFRb0fHpb8NuC5iQx4UKtPkJf8',
    appId: '1:291688942373:ios:4201e0e11512dd54a1a8cc',
    messagingSenderId: '291688942373',
    projectId: 'gdsc-53961',
    storageBucket: 'gdsc-53961.appspot.com',
    iosBundleId: 'com.example.gdsc.RunnerTests',
  );
}
